---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts:
    - controller
    - compute1
    - block1
    # - object1
    # - object2
  become: true
  roles:
    - common

- name: apply configuration to controller node
  hosts:
    - controller
  become: true
  roles:
    - controller

- name: apply configuration to compute nodes
  hosts:
    - compute
  become: true
  roles:
    - compute

- name: apply configuration to block nodes
  hosts:
    - block1
  become: true
  roles:
    - block

#- name: apply configuration to object nodes
#  hosts: object
#  become: true
#
#  roles:
#  - object
