---

- name: install and configure cinder
  command: "{{ item }}"
  with_items:
    - openstack user create --domain default --password {{ CINDER_PASS }} cinder
    - openstack role add --project service --user cinder admin
    - openstack service create --name cinder --description "OpenStack Block Storage" volume
    - openstack service create --name cinderv2 --description "OpenStack Block Storage" volumev2
    - openstack endpoint create --region RegionOne volume public http://controller:8776/v1/%\(tenant_id\)s
    - openstack endpoint create --region RegionOne volume internal http://controller:8776/v1/%\(tenant_id\)s
    - openstack endpoint create --region RegionOne volume admin http://controller:8776/v1/%\(tenant_id\)s
    - openstack endpoint create --region RegionOne volumev2 public http://controller:8776/v2/%\(tenant_id\)s
    - openstack endpoint create --region RegionOne volumev2 internal http://controller:8776/v2/%\(tenant_id\)s
    - openstack endpoint create --region RegionOne volumev2 admin http://controller:8776/v2/%\(tenant_id\)s
  become: true
  become_user: openstack
  environment:
    OS_PROJECT_DOMAIN_NAME: "{{ OS_PROJECT_DOMAIN_NAME }}"
    OS_USER_DOMAIN_NAME: "{{ OS_USER_DOMAIN_NAME }}"
    OS_PROJECT_NAME: "{{ OS_PROJECT_NAME }}"
    OS_USERNAME: "{{ OS_USERNAME }}"
    OS_PASSWORD: "{{ OS_PASSWORD }}"
    OS_AUTH_URL: "{{ OS_AUTH_URL }}"
    OS_IDENTITY_API_VERSION: "{{ OS_IDENTITY_API_VERSION }}"
    OS_IMAGE_API_VERSION: "{{ OS_IMAGE_API_VERSION }}"

- name: create /etc/cinder/cinder.conf file
  template: src=cinder.conf.j2 dest=/etc/cinder/cinder.conf owner=cinder group=cinder mode=0644 backup=yes

- name: populate block storage database
  command: su -s /bin/sh -c "cinder-manage db sync" cinder

- name: restart nova-api
  service: name=nova-api state=restarted

- name: restart cinder-scheduler
  service: name=cinder-scheduler state=restarted

- name: restart cinder-api
  service: name=cinder-api state=restarted
