---

- name: install and configure glance
  command: "{{ item }}"
  with_items:
    - openstack user create --domain default --password {{ GLANCE_PASS }} glance
    - openstack role add --project service --user glance admin
    - openstack service create --name glance --description "OpenStack Image" image
    - openstack endpoint create --region RegionOne image public http://controller:9292
    - openstack endpoint create --region RegionOne image internal http://controller:9292
    - openstack endpoint create --region RegionOne image admin http://controller:9292
  become: true
  become_user: openstack
  environment:
    OS_PROJECT_DOMAIN_NAME: "{{ OS_PROJECT_DOMAIN_NAME }}"
    OS_USER_DOMAIN_NAME: "{{ OS_USER_DOMAIN_NAME }}"
    OS_PROJECT_NAME: "{{ OS_PROJECT_NAME }}"
    OS_USERNAME: "{{ OS_USERNAME }}"
    OS_PASSWORD: "{{ OS_PASSWORD }}"
    OS_AUTH_URL: "{{ OS_AUTH_URL }}"
    OS_IDENTITY_API_VERSION: "{{ OS_IDENTITY_API_VERSION }}"
    OS_IMAGE_API_VERSION: "{{ OS_IMAGE_API_VERSION }}"

- name: create /etc/glance/glance-api.conf file
  template: src=glance-api.conf.j2 dest=/etc/glance/glance-api.conf owner=glance group=glance mode=0644 backup=yes

- name: create /etc/glance/glance-registry.conf file
  template: src=glance-registry.conf.j2 dest=/etc/glance/glance-registry.conf owner=glance group=glance mode=0644 backup=yes

- name: populate image service database
  command: su -s /bin/sh -c "glance-manage db_sync" glance

- name: restart glance-registry
  service: name=glance-registry state=restarted

- name: restart glance-api
  service: name=glance-api state=restarted
