---
# tasks file for controller

- name: install packages
  apt: name={{ item }} state=present
  with_items:
    - mariadb-server
    - python-pymysql
    - python-mysqldb
    - rabbitmq-server
    - memcached
    - python-memcache
    - keystone
    - glance
    - nova-api
    - nova-consoleauth
    - nova-conductor
    - nova-novncproxy
    - nova-scheduler
    - neutron-server
    - neutron-plugin-ml2
    - neutron-linuxbridge-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - openstack-dashboard
    - cinder-api
    - cinder-scheduler
    # - manila-api
    # - manila-scheduler
    # - python-manilaclient

- include: chrony_basic_conf.yml

- include: mariadb_basic_conf.yml

- include: rabbitmq_keystone_conf.yml

- include: memcached_basic_conf.yml

- include: mariadb_keystone_conf.yml

- include: keystone_conf.yml

- include: keystone_elements.yml

- include: mariadb_glance_conf.yml

- include: glance_conf.yml

- include: mariadb_nova_conf.yml

- include: nova_conf.yml

- include: mariadb_neutron_conf.yml

- include: neutron_conf.yml

- include: dashboard_conf.yml

- include: mariadb_cinder_conf.yml

- include: cinder_conf.yml

# - include: mariadb_manila_conf.yml

# - include: manila_conf.yml
