---

- name: set memcached configuration for openstack
  template: src=memcached.conf.j2 dest=/etc/memcached.conf owner=root group=root mode=0644 backup=yes

- name: restart memcached
  service: name=memcached state=restarted
