---

- name: install and configure neutron
  command: "{{ item }}"
  with_items:
    - openstack user create --domain default --password {{ NEUTRON_PASS }} neutron
    - openstack role add --project service --user neutron admin
    - openstack service create --name neutron --description "OpenStack Networking" network
    - openstack endpoint create --region RegionOne network public http://controller:9696
    - openstack endpoint create --region RegionOne network internal http://controller:9696
    - openstack endpoint create --region RegionOne network admin http://controller:9696
  become: true
  become_user: openstack
  environment:
    OS_PROJECT_DOMAIN_NAME: "{{ OS_PROJECT_DOMAIN_NAME }}"
    OS_USER_DOMAIN_NAME: "{{ OS_USER_DOMAIN_NAME }}"
    OS_PROJECT_NAME: "{{ OS_PROJECT_NAME }}"
    OS_USERNAME: "{{ OS_USERNAME }}"
    OS_PASSWORD: "{{ OS_PASSWORD }}"
    OS_AUTH_URL: "{{ OS_AUTH_URL }}"
    OS_IDENTITY_API_VERSION: "{{ OS_IDENTITY_API_VERSION }}"
    OS_IMAGE_API_VERSION: "{{ OS_IMAGE_API_VERSION }}"

- name: create /etc/neutron/neutron.conf file
  template: src=neutron.conf.j2 dest=/etc/neutron/neutron.conf owner=root group=neutron mode=0640

- name: create /etc/neutron/plugins/ml2/ml2_conf.ini file
  template: src=ml2_conf.ini.j2 dest=/etc/neutron/plugins/ml2/ml2_conf.ini owner=root group=neutron mode=0644

- name: create /etc/neutron/plugins/ml2/linuxbridge_agent.ini file
  template: src=linuxbridge_agent.ini.j2 dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini owner=root group=neutron mode=0644

- name: create /etc/neutron/l3_agent.ini file
  copy: src=l3_agent.ini dest=/etc/neutron/l3_agent.ini owner=root group=neutron mode=0644

- name: create /etc/neutron/dhcp_agent.ini file
  copy: src=dhcp_agent.ini dest=/etc/neutron/dhcp_agent.ini owner=root group=neutron mode=0644

- name: create /etc/neutron/metadata_agent.ini file
  template: src=metadata_agent.ini.j2 dest=/etc/neutron/metadata_agent.ini owner=root group=neutron mode=0644

- name: populate neutron database
  command: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron

- name: restart nova-api
  service: name=nova-api state=restarted

- name: restart neutron-server
  service: name=neutron-server state=restarted

- name: restart neutron-linuxbridge-agent
  service: name=neutron-linuxbridge-agent state=restarted

- name: restart neutron-dhcp-agent
  service: name=neutron-dhcp-agent state=restarted

- name: restart neutron-metadata-agent
  service: name=neutron-metadata-agent state=restarted

- name: restart neutron-l3-agent
  service: name=neutron-l3-agent state=restarted
