---

- name: create /etc/neutron/neutron.conf file
  template: src=neutron.conf.j2 dest=/etc/neutron/neutron.conf owner=root group=neutron mode=0640 backup=yes

- name: create /etc/neutron/plugins/ml2/linuxbridge_agent.ini file
  template: src=linuxbridge_agent.ini.j2 dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini owner=root backup=yes group=neutron mode=0644

- name: restart neutron-linuxbridge-agent
  service: name=neutron-linuxbridge-agent state=restarted
